# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-file-stage:
    image: mongo:4.2.0
    container_name: mongo-file-stage
    ports:
      - '5555:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-file-stage:
    build: .
    #image: christroutner/ipfs-service-provider:v5.0.1
    container_name: ipfs-file-stage
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 4000mb
    links:
      - mongo-file-stage
    ports:
      - '5040:5040' # <host port>:<container port>
      - '4001:4001'
      - '4003:4003'
    volumes:
      - ../data/ipfsdata:/home/safeuser/ipfs-file-stager/.ipfsdata
      - ./start-production.sh:/home/safeuser/ipfs-file-stager/start-production.sh
    restart: always
